NAME_MAP_2 = {
    'de Kock (wk)': 'Quinton de Kock',
    'Narine': 'Sunil Narine',
    'Ajinkya Rahane (c)': 'Ajinkya Rahane',
    'Russell': 'Andre Russell',
    'Ramandeep Singh': 'Ramandeep Singh ',
    'Rajat Patidar (c)': 'Rajat Patidar',
    'Hazlewood': 'Josh Hazlewood',
    'Rasikh Salam': 'Rasikh Dar Salam',
    'Livingstone': 'Liam Livingstone',
    'Head': 'Travis Head',
    'Nitish Reddy': 'Nitish Kumar Reddy',
    'Klaasen (wk)': 'Heinrich Klaasen',
    'Cummins (c)': 'Pat Cummins',
    'Riyan Parag (c)': 'Riyan Parag',
    'Dhruv Jurel (wk)': 'Dhruv Jurel',
    'M Theekshana': 'Maheesh Theekshana',
    'Pat Cummins (c)': 'Pat Cummins',
    'Rohit': 'Rohit Sharma',
    'Rickelton (wk)': 'Ryan Rickelton',
    'Suryakumar Yadav (c)': 'Suryakumar Yadav',
    'Santner': 'Mitchell Santner',
    'D Chahar': 'Deepak Chahar',
    'Boult': 'Trent Boult',
    'Ruturaj Gaikwad (c)': 'Ruturaj Gaikwad',
    'MS Dhoni (wk)': 'MS Dhoni',
    'Ashwin': 'Ravichandran Ashwin',
    'Markram': 'Aiden Markram',
    'Pooran': 'Nicholas Pooran',
    'Pant (c & wk)': 'Rishabh Pant',
    'Thakur': 'Shardul Thakur',
    'Abishek Porel (wk)': 'Abishek Porel',
    'Sameer Rizvi': 'Sameer Rizvi ',
    'Axar Patel (c)': 'Axar Patel',
    'Axar (c)': 'Axar Patel',
    'Stubbs': 'Tristan Stubbs',
    'Prabhsimran (wk)': 'Prabhsimran Singh',
    'Shreyas Iyer (c)': 'Shreyas Iyer',
    'Azmatullah': 'Azmatullah Omarzai',
    'Maxwell': 'Glenn Maxwell',
    'Stoinis': 'Marcus Stoinis',
    'Shubman Gill (c)': 'Shubman Gill',
    'Jos Buttler (wk)': 'Jos Buttler',
    'Siraj': 'Mohammed Siraj',
    'Rabada': 'Kagiso Rabada',
    'Prasidh': 'Prasidh Krishna',
    'Sai Kishore': 'Ravisrinivasan Sai Kishore',
    'Samson': 'Sanju Samson',
    'W Hasaranga': 'Wanindu Hasaranga',
    'Hetmyer': 'Shimron Hetmyer',
    'Quinton de Kock (wk)': 'Quinton de Kock',
    'Moeen': 'Moeen Ali',
    'Dhoni': 'MS Dhoni',
    'Jitesh Sharma (wk)': 'Jitesh Sharma',
    'Shami': 'Mohammed Shami',
    'du Plessis': 'Faf du Plessis',
    'Rahul': 'KL Rahul',
    'Axar': 'Axar Patel',
    'Thakur': 'Shardul Thakur',
    'Natarajan': 'T Natarajan',
    'Bishnoi': 'Ravi Bishnoi',
    'Bumrah': 'Jasprit Bumrah',
    'Curran': 'Sam Curran',
    'Dube': 'Shivam Dube',
    'Pant': 'Rishabh Pant',
    'Patidar': 'Rajat Patidar',
    'Kishan': 'Ishan Kishan',
    'Rabada': 'Kagiso Rabada',
    'Jansen': 'Marco Jansen',
    'Sudarsan': 'Sai Sudharsan',
    'Klaasen': 'Heinrich Klaasen',
    'Rahane': 'Ajinkya Rahane',
    'Salt': 'Phil Salt',
    'Chakravarthy': 'Varun Chakravarthy',
    'Siraj': 'Mohammed Siraj',
    'Parag': 'Riyan Parag',
    'Tripathi': 'Rahul Tripathi',
    'Kohli': 'Virat Kohli',
    'Pooran': 'Nicholas Pooran',
    'Buttler': 'Jos Buttler',
    'Jurel': 'Dhruv Jurel',
    'Sanju': 'Sanju Samson',
    'Samson': 'Sanju Samson',
    'Samson (c)': 'Sanju Samson',
    'Chahal': 'Yuzvendra Chahal',
    'Boult': 'Trent Boult',
    'Jadeja': 'Ravindra Jadeja',
    'Livingstone': 'Liam Livingstone',
    'Philip Salt': 'Phil Salt',

}

NAME_MAP_3 = {
    "Rohit Sharma": ["R Sharma", "Sharma", "Rohit"],
    "Shubman Gill": ["S Gill", "Gill"],
    "KL Rahul": ["Rahul", "K L Rahul", "K Rahul"],
    "Faf du Plessis": ["F du Plessis", "du Plessis", "Faf"],
    "Arshdeep Singh": ["A Singh", "Arshdeep"],
    "T Natarajan": ["Natarajan", "T Natarajan"],
    "Ravi Bishnoi": ["R Bishnoi", "Bishnoi"],
    "Sunil Narine": ["S Narine", "Narine"],
    "Krunal Pandya": ["K Pandya", "Krunal"],
    "Sam Curran": ["S Curran", "Curran"],
    "Rishabh Pant": ["R Pant", "Pant"],
    "MS Dhoni": ["Dhoni", "M Dhoni", "M S Dhoni"],
    "Tristan Stubbs": ["T Stubbs", "Stubbs"],
    "Pat Cummins": ["P Cummins", "Cummins"],
    "Mohammed Shami": ["M Shami", "Shami"],
    "Anshul Kambhoj": ["A Kambhoj", "Kambhoj"],
    "Karn Sharma": ["K Sharma", "Karn"],
    "Ruturaj Gaikwad": ["R Gaikwad", "Gaikwad"],
    "Travis Head": ["T Head", "Head"],
    "Rajat Patidar": ["R Patidar", "Patidar"],
    "Abhishek Sharma": ["A Sharma", "Abhishek"],
    "Ishan Kishan": ["I Kishan", "Kishan"],
    "Jitesh Sharma": ["J Sharma", "Jitesh"],
    "Jasprit Bumrah": ["J Bumrah", "Bumrah"],
    "Kagiso Rabada": ["K Rabada", "Rabada"],
    "Bhuvneshwar Kumar": ["B Kumar", "Bhuvneshwar", "Bhuvi"],
    "Marco Jansen": ["M Jansen", "Jansen"],
    "Sai Sudharsan": ["S Sudharsan", "Sudharsan"],
    "Shivam Dube": ["S Dube", "Dube"],
    "Ravichandran Ashwin": ["R Ashwin", "Ashwin"],
    "Tilak Varma": ["T Varma", "Varma"],
    "Rashid Khan": ["R Khan", "Rashid"],
    "Suryakumar Yadav": ["S Yadav", "Suryakumar", "SKY"],
    "Heinrich Klaasen": ["H Klaasen", "Klaasen"],
    "Ajinkya Rahane": ["A Rahane", "Rahane"],
    "Philip Salt": ["P Salt", "Phil Salt", "Salt"],
    "Varun Chakaravarthy": ["V Chakaravarthy", "Varun"],
    "Josh Hazlewood": ["J Hazlewood", "Hazlewood"],
    "Khaleel Ahmed": ["K Ahmed", "Khaleel"],
    "Mohammed Siraj": ["M Siraj", "Siraj"],
    "Glenn Maxwell": ["G Maxwell", "Maxwell"],
    "Axar Patel": ["A Patel", "Axar"],
    "Riyan Parag": ["R Parag", "Parag"],
    "Andre Russell": ["A Russell", "Russell"],
    "Hardik Pandya": ["H Pandya", "Hardik"],
    "Nitish Kumar Reddy": ["N Reddy", "Nitish Reddy"],
    "Shreyas Iyer": ["S Iyer", "Iyer"],
    "Rahul Tripathi": ["R Tripathi", "Tripathi"],
    "Virat Kohli": ["V Kohli", "Kohli"],
    "Nicholas Pooran": ["N Pooran", "Pooran"],
    "Jos Buttler": ["J Buttler", "Buttler"],
    "Karun Nair": ["K Nair", "Karun"],
    "Sanju Samson": ["S Samson", "Samson"],
    "Rinku Singh": ["R Singh", "Rinku"],
    "Yuzvendra Chahal": ["Y Chahal", "Chahal"],
    "Trent Boult": ["T Boult", "Boult"],
    "Kuldeep Yadav": ["K Yadav", "Kuldeep"],
    "Marcus Stoinis": ["M Stoinis", "Stoinis"],
    "Ravindra Jadeja": ["R Jadeja", "Jadeja"],
    "Liam Livingstone": ["L Livingstone", "Livingstone"],
    "Abhishek Porel": ["A Porel", "Porel"],
    "Dhruv Jurel": ["D Jurel", "Jurel"],
    "Rachin Ravindra": ["R Ravindra", "Rachin"],
    "Mohit Sharma": ["M Sharma", "Mohit"],
    "Ashutosh Sharma": ["A Sharma", "Ashutosh"]
}

SQUADS = {
    'Aksh': [
        'Ajinkya Rahane',
        'Philip Salt',
        'Suryakumar Yadav',
        'Heinrich Klaasen',
        'Andre Russell',
        'Glenn Maxwell',
        'Hardik Pandya',
        'Shreyas Iyer',
        'Riyan Parag',
        'Varun Chakaravarthy',
        'Josh Hazlewood',
        'Nitish Kumar Reddy',
        'Rahul Tripathi',
        'Axar Patel',
        'Mohammed Siraj',
        'Khaleel Ahmed'
    ],
    'Dishaan': [
        'Rachin Ravindra',
        'Virat Kohli',
        'Jos Buttler',
        'Nicholas Pooran',
        'Sanju Samson',
        'Dhruv Jurel',
        'Ashutosh Sharma',
        'Liam Livingstone',
        'Marcus Stoinis',
        'Kuldeep Yadav',
        'Trent Boult',
        'Abhishek Porel',
        'Rinku Singh',
        'Ravindra Jadeja',
        'Mohit Sharma',
        'Yuzvendra Chahal',
        'Karun Nair'
    ],
    'Soupreet': [
        'Travis Head',
        'Ishan Kishan',
        'Ruturaj Gaikwad',
        'Abhishek Sharma',
        'Tilak Varma',
        'Rajat Patidar',
        'Sai Sudharsan',
        'Rashid Khan',
        'Marco Jansen',
        'Bhuvneshwar Kumar',
        'Kagiso Rabada',
        'Jitesh Sharma',
        'Jasprit Bumrah',
        'Ravichandran Ashwin',
        'Shivam Dube'
    ],
    'Vedant': [
        'Rohit Sharma',
        'Shubman Gill',
        'KL Rahul',
        'Faf du Plessis',
        'Arshdeep Singh',
        'T Natarajan',
        'Ravi Bishnoi',
        'Sunil Narine',
        'Krunal Pandya',
        'Sam Curran',
        'Rishabh Pant',
        'MS Dhoni',
        'Tristan Stubbs',
        'Pat Cummins',
        'Mohammed Shami',
        'Anshul Kambhoj',
        'Karn Sharma'
    ]
}

D11_TEAMS = {
    'Aksh': {
        'Team': [
            'Ajinkya Rahane',
            'Philip Salt',
            'Suryakumar Yadav',
            'Heinrich Klaasen',
            'Andre Russell',
            'Glenn Maxwell',
            'Hardik Pandya',
            'Shreyas Iyer',
            'Riyan Parag',
            'Varun Chakaravarthy',
            'Josh Hazlewood'
        ],
        'Captain': 'Glenn Maxwell',
        'Vice Captain': 'Shreyas Iyer'
    },
    'Dishaan': {
        'Team': [
            'Rachin Ravindra',
            'Virat Kohli',
            'Jos Buttler',
            'Nicholas Pooran',
            'Sanju Samson',
            'Dhruv Jurel',
            'Ashutosh Sharma',
            'Liam Livingstone',
            'Marcus Stoinis',
            'Kuldeep Yadav',
            'Trent Boult'
        ],
        'Captain': 'Nicholas Pooran',
        'Vice Captain': 'Virat Kohli'
    },
    'Soupreet': {
        'Team': [
            'Travis Head',
            'Ishan Kishan',
            'Ruturaj Gaikwad',
            'Abhishek Sharma',
            'Tilak Varma',
            'Rajat Patidar',
            'Sai Sudharsan',
            'Rashid Khan',
            'Marco Jansen',
            'Bhuvneshwar Kumar',
            'Kagiso Rabada'
        ],
        'Captain': 'Ishan Kishan',
        'Vice Captain': 'Ruturaj Gaikwad'
    },
    'Vedant': {
        'Team': [
            'Shubman Gill',
            'Sunil Narine',
            'Faf du Plessis',
            'KL Rahul',
            'Rishabh Pant',
            'Tristan Stubbs',
            'Krunal Pandya',
            'Sam Curran',
            'Ravi Bishnoi',
            'Pat Cummins',
            'Arshdeep Singh'
        ],
        'Captain': 'Sunil Narine',
        'Vice Captain': 'Shubman Gill'
    }
}

RESTRICTED_TEAMS = {
    'Aksh': {
        'Team': [
            'Philip Salt',
            'Ajinkya Rahane',
            'Shreyas Iyer',
            'Suryakumar Yadav',
            'Heinrich Klaasen',
            'Glenn Maxwell',
            'Hardik Pandya',
            'Axar Patel',
            'Josh Hazlewood',
            'Varun Chakaravarthy',
            'Khaleel Ahmed'
        ],
        'Captain': 'Shreyas Iyer',
        'Vice Captain': 'Hardik Pandya'
    },
    'Dishaan': {
        'Team': [
            'Rachin Ravindra',
            'Virat Kohli',
            'Sanju Samson',
            'Nicholas Pooran',
            'Dhruv Jurel',
            'Marcus Stoinis',
            'Ashutosh Sharma',
            'Ravindra Jadeja',
            'Trent Boult',
            'Kuldeep Yadav',
            'Yuzvendra Chahal'
        ],
        'Captain': 'Nicholas Pooran',
        'Vice Captain': 'Virat Kohli'
    },
    'Soupreet': {
        'Team': [
            'Ruturaj Gaikwad',
            'Travis Head',
            'Ishan Kishan',
            'Rajat Patidar',
            'Tilak Varma',
            'Jitesh Sharma',
            'Shivam Dube',
            'Ravichandran Ashwin',
            'Rashid Khan',
            'Bhuvneshwar Kumar',
            'Kagiso Rabada'
        ],
        'Captain': 'Travis Head',
        'Vice Captain': 'Rajat Patidar'
    },
    'Vedant': {
        'Team': [
            'Rohit Sharma',
            'Shubman Gill',
            'KL Rahul',
            'Faf du Plessis',
            'Tristan Stubbs',
            'Rishabh Pant',
            'Sunil Narine',
            'Krunal Pandya',
            'Pat Cummins',
            'Arshdeep Singh',
            'Mohammed Shami'
        ],
        'Captain': 'Sunil Narine',
        'Vice Captain': 'Shubman Gill'
    }
}

NAME_MAP = {
    "Rohit Sharma": ["R Sharma", "Sharma", "Rohit"],
    "Shubman Gill": ["S Gill", "Gill"],
    "KL Rahul": ["Rahul", "K L Rahul", "K Rahul"],
    "Faf du Plessis": ["F du Plessis", "du Plessis", "Faf"],
    "Arshdeep Singh": ["A Singh", "Arshdeep"],
    "T Natarajan": ["Natarajan", "T Natarajan"],
    "Ravi Bishnoi": ["R Bishnoi", "Bishnoi"],
    "Sunil Narine": ["S Narine", "Narine"],
    "Krunal Pandya": ["K Pandya", "Krunal"],
    "Sam Curran": ["S Curran", "Curran"],
    "Rishabh Pant": ["R Pant", "Pant"],
    "MS Dhoni": ["Dhoni", "M Dhoni", "M S Dhoni"],
    "Tristan Stubbs": ["T Stubbs", "Stubbs"],
    "Pat Cummins": ["P Cummins", "Cummins"],
    "Mohammed Shami": ["M Shami", "Shami"],
    "Anshul Kambhoj": ["A Kambhoj", "Kambhoj"],
    "Karn Sharma": ["K Sharma", "Karn"],
    "Ruturaj Gaikwad": ["R Gaikwad", "Gaikwad"],
    "Travis Head": ["T Head", "Head"],
    "Rajat Patidar": ["R Patidar", "Patidar"],
    "Abhishek Sharma": ["A Sharma", "Abhishek"],
    "Ishan Kishan": ["I Kishan", "Kishan"],
    "Jitesh Sharma": ["J Sharma", "Jitesh"],
    "Jasprit Bumrah": ["J Bumrah", "Bumrah"],
    "Kagiso Rabada": ["K Rabada", "Rabada"],
    "Bhuvneshwar Kumar": ["B Kumar", "Bhuvneshwar", "Bhuvi"],
    "Marco Jansen": ["M Jansen", "Jansen"],
    "Sai Sudharsan": ["S Sudharsan", "Sudharsan"],
    "Shivam Dube": ["S Dube", "Dube"],
    "Ravichandran Ashwin": ["R Ashwin", "Ashwin"],
    "Tilak Varma": ["T Varma", "Varma"],
    "Rashid Khan": ["R Khan", "Rashid"],
    "Suryakumar Yadav": ["S Yadav", "Suryakumar", "SKY"],
    "Heinrich Klaasen": ["H Klaasen", "Klaasen"],
    "Ajinkya Rahane": ["A Rahane", "Rahane"],
    "Philip Salt": ["P Salt", "Phil Salt", "Salt"],
    "Varun Chakravarthy": ["V Chakravarthy", "Varun"],
    "Josh Hazlewood": ["J Hazlewood", "Hazlewood"],
    "Khaleel Ahmed": ["K Ahmed", "Khaleel"],
    "Mohammed Siraj": ["M Siraj", "Siraj"],
    "Glenn Maxwell": ["G Maxwell", "Maxwell"],
    "Axar Patel": ["A Patel", "Axar"],
    "Riyan Parag": ["R Parag", "Parag"],
    "Andre Russell": ["A Russell", "Russell"],
    "Hardik Pandya": ["H Pandya", "Hardik"],
    "Nitish Kumar Reddy": ["N Reddy", "Nitish Reddy"],
    "Shreyas Iyer": ["S Iyer", "Iyer"],
    "Rahul Tripathi": ["R Tripathi", "Tripathi"],
    "Virat Kohli": ["V Kohli", "Kohli"],
    "Nicholas Pooran": ["N Pooran", "Pooran"],
    "Jos Buttler": ["J Buttler", "Buttler"],
    "Karun Nair": ["K Nair", "Karun"],
    "Sanju Samson": ["S Samson", "Samson"],
    "Rinku Singh": ["R Singh", "Rinku"],
    "Yuzvendra Chahal": ["Y Chahal", "Chahal"],
    "Trent Boult": ["T Boult", "Boult"],
    "Kuldeep Yadav": ["K Yadav", "Kuldeep"],
    "Marcus Stoinis": ["M Stoinis", "Stoinis"],
    "Ravindra Jadeja": ["R Jadeja", "Jadeja"],
    "Liam Livingstone": ["L Livingstone", "Livingstone"],
    "Abhishek Porel": ["A Porel", "Porel"],
    "Dhruv Jurel": ["D Jurel", "Jurel"],
    "Rachin Ravindra": ["R Ravindra", "Rachin"],
    "Mohit Sharma": ["M Sharma", "Mohit"],
    "Ashutosh Sharma": ["A Sharma", "Ashutosh"]
}
